title = "eric hambro"
baseURL = "https://condnsdmatters.github.io"
languageCode = "en-us"
theme = ""
themesDir = ""

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 20 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/erichammy"
  instagram = ""
  youtube = ""
  github = "https://github.com/condnsdmatters"
  gitlab = ""
  linkedin = "https://linkedin.com/in/eric-hambro"
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/sky.jpg"
  recent_posts_number = 1
