title = "eric hambro"
baseURL = "https://erichambro.com"
languageCode = "en-us"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "../resources"
themesDir = ""

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 20 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "eric hambro"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The personal site of Eric Hambro."
  facebook = ""
  twitter = "https://twitter.com/erichammy"
  instagram = ""
  youtube = ""
  github = "https://github.com/cdmatters"
  gitlab = ""
  linkedin = "https://linkedin.com/in/eric-hambro"
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/sky.jpg"
  recent_posts_number = 1


[[params.ananke_socials]]
name = "scholar"
url = "https://scholar.google.com/citations?user=ehquBPIAAAAJ&hl=en&oi=ao"
color = "#ff6800"
label = "Google Scholar"
